[package]
name = "bunny_sniper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
